### ISSUE TITLE
Batch operations

### ISSUE THREAD

**Issue by mainakae** [ScorpioBroker/ScorpioBroker#38] opened 2019-11-18 09:45 UTC
Hello everyone.

Hello, we are trying to use batch operations with no success.

Are they implemented?

Best regards,
Pedro.

**Comment by ScorpioBroker** [comment] 2019-11-18 09:47
Hi yes, they are implemented. You'll need to rebuild the gateway as well since it's a new resource mapping. It's not in the current docker image on docker hub yet.

**Comment by MS-Fiware** [comment] 2019-11-18 10:31
Duplicate of closed issue #15 ?

**Comment by mainakae** [comment] 2019-11-18 12:03
> Duplicate of closed issue #15 ?

Not exactly, we also tried delte, upsert and update. :)

**Closed** 2019-11-18 13:20 UTC
